# Compiler
CC = nvcc

# .cu files
CFILES = devicequery.cu

query:
	$(CC) $(CFILES) -o devicequery



# # Compiler
# # CC = gcc
# CC = nvcc

# # Compiler Flags: Use $(CF) for generic/old architectures
# CF     = -g -O2
# # CFLAGS = -ansi -std=gnu99
# # CFLAGS = -std=c11
# CFLAGS_1 = -ansi -pedantic -std=gnu99 -Wall -W
# CFLAGS_2 = -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -g -O2

# # Objects
# CFILES = cuda_device_query2.cu

# # MACRO1 = -D

# # %.o : %.c
# # 	$(CC) $(CFLAGS) -c $<

# # example1:
# # 	$(CC) $(CF) $(CFLAGS) $(CFILES) -lm -o run_prog
# example1:
# 	$(CC) $(CFILES)

# clean:
# 	rm -r *.o run_prog*

# run:
# 	./run_prog
