#!/bin/bash
#PBS -l nodes=1:ppn=1:xxnodexx
#PBS -N xxsubnamexx
# #PBS -l walltime=300:00:00

# Fix environment variables.
USER=xxuserxx # self.user
MY_DIR=xxmy_dirxx # self.cwd
JOB_DIR_NAME=xxjob_dir_namexx # self.job_dir_name
JOB_PATH_LOCAL=xxjob_path_localxx # self.job_path_local
JOB_PATH_RUN=xxjob_path_runxx # self.job_path_run # /scratch/user/$JOB_SUB
JOB_COMPLETED_DIR=xxcompleted_dirxx # self.completed_dir # /data4/user/completed/$JOB_SUB

# Prepare directories.
rm -rf $JOB_PATH_RUN
mkdir -p $JOB_PATH_RUN
cp $JOB_PATH_LOCAL/* $JOB_PATH_RUN
cd $JOB_PATH_RUN

# Job Execution.
# compile
# gcc -O2 main_pullends_fullGo_dcd_nucl.c read_protein.c rforce.c force_pullends_nucl.c iteration_nucl.c update_dcd_fullGo_nucl.c ras_structure_nucl.c identify.c dcdio.c -lm -Wall -o run_protein_Fene */
# make main:
#     $(CC) $(CFLAGS_1) $(CFLAGS_2) $(CFILES) -lm -o run_protein
# make run:
# ./run_protein_Fene pdb Contacts_map(combined) seed(1)
# ./run_protein pdbADP4B9Q.pdb Contacts_intra_inter_b_ADP4B9Q_j29 1

# cd $JOB_DIR
mkdir Coord
mkdir Struct_data
# chmod +x *run_protein*

STARTTIME=$(date +%s)
#./xxrunxx xxpdbxx xxcontactxx xxseedxx
./run_protein xxpdbxx xxcontactxx xxseedxx
# make xxargv_onexx
# make run
wait
ENDTIME=$(date +%s)
TOTALTIME=$(($ENDTIME-$STARTTIME))

echo $TOTALTIME >> soptime.dat
# printf "%d\n" $TOTALTIME
# printf "%0.2f\n" $TOTALTIME

# Clean up!
rsync -auvz $JOB_PATH_RUN/* $JOB_COMPLETED_DIR
#rm -rf $JOB_DIR
