#/bin/bash

# COMMAND="yum install"
COMMAND="pacman -S"

defaults () {
    $COMMAND nmtui
    $COMMAND intltool
    $COMMAND kernel-headers-$(uname -r)
    $COMMAND kernel-devel-$(uname -r)
    $COMMAND dkms
    $COMMAND wget make gcc-c++ freeglut-devel libXi-devel libXmu-devel mesa-libGLU-devel
    $COMMAND bumblebee-nvidia bbswitch-dkms VirtualGL.x86_64 VirtualGL.i686 primus.x86_64 primus.i686 kernel-devel
}


# blacklist nouveau (/etc/modprobe.d/nvidia-installer-disable-nouveau.conf)
#   # generated by nvidia-installer
#   blacklist nouveau
#   options nouveau modeset=0
# download nvidia-driver and cuda.run separately.
# systemctl stop gdm
# alt-F2
# su
# install nvidia-driver
# mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r).img.bak
# dracut -v /boot/initramfs-$(uname -r).img $(uname -r)

packages_general () {
  $COMMAND vim
  $COMMAND emacs
  $COMMAND terminator
  $COMMAND geeqie 
  $COMMAND python2-numpy
  $COMMAND python3-numpy
}



defaults
# packages_general
